function [ddqm,ddqf] = autoGen_dynamics(qm,dqm,qf,dqf,Tm,Jm,Ks,Jf,Kf)
%AUTOGEN_DYNAMICS
%    [DDQM,DDQF] = AUTOGEN_DYNAMICS(QM,DQM,QF,DQF,TM,JM,KS,JF,KF)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Aug-2015 09:32:45

t2 = Ks.*qf;
ddqm = (Tm+t2-Ks.*qm)./Jm;
if nargout > 1
    ddqf = -(t2-Ks.*qm+Kf.*sin(qf))./Jf;
end
