function [AA,bb] = autoGen_dynamics_contact(q0,q1,dq1,dq0,ddpc_x,ddpc_y,th,m0,m1,g,r,a,b,I0,I1)
%AUTOGEN_DYNAMICS_CONTACT
%    [AA,BB] = AUTOGEN_DYNAMICS_CONTACT(Q0,Q1,DQ1,DQ0,DDPC_X,DDPC_Y,TH,M0,M1,G,R,A,B,I0,I1)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 13:11:36

t2 = -m0-m1;
t3 = cos(q0);
t4 = cos(q1);
t5 = sin(q0);
t6 = sin(q1);
t7 = a.*t3;
t8 = b.*t4;
t9 = t7+t8;
t10 = a.*t5;
t11 = b.*t6;
t12 = t10+t11;
t13 = q0+th;
t14 = b.^2;
t15 = cos(t13);
t16 = r.*t15;
t17 = sin(t13);
t18 = r.*t17;
AA = reshape([t2,0.0,-m1.*t9,-b.*m1.*t4,1.0,0.0,0.0,t2,-m1.*t12,-b.*m1.*t6,0.0,1.0,-a.*m1.*t3,-a.*m1.*t5,-I0-a.*m1.*t3.*t9-a.*m1.*t5.*t12,-a.*b.*m1.*t3.*t4-a.*b.*m1.*t5.*t6,t16,t18,-b.*m1.*t4,-b.*m1.*t6,-I1-b.*m1.*t4.*t9-b.*m1.*t6.*t12,-I1-m1.*t4.^2.*t14-m1.*t6.^2.*t14,0.0,0.0,1.0,0.0,t16,0.0,0.0,0.0,0.0,1.0,t18,0.0,0.0,0.0],[6, 6]);
if nargout > 1
    t19 = dq0.^2;
    t20 = dq1.^2;
    t21 = a.*t3.*t19;
    t22 = b.*t4.*t20;
    t23 = t21+t22;
    t24 = a.*t5.*t19;
    t25 = b.*t6.*t20;
    t26 = t24+t25;
    bb = [-m1.*t26;g.*m0+g.*m1+m1.*t23;g.*m1.*t12-m1.*t9.*t26+m1.*t12.*t23;b.*g.*m1.*t6+b.*m1.*t6.*t23-b.*m1.*t4.*t26;ddpc_x+r.*t17.*t19;ddpc_y-r.*t15.*t19];
end
