function [p0,pStar,p1,dp0,dpStar,dp1] = autoGen_kinematics_minimal(q0,q1,dq1,dq0,r,a,b,slope)
%AUTOGEN_KINEMATICS_MINIMAL
%    [P0,PSTAR,P1,DP0,DPSTAR,DP1] = AUTOGEN_KINEMATICS_MINIMAL(Q0,Q1,DQ1,DQ0,R,A,B,SLOPE)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 10:05:38

t2 = cos(slope);
t3 = sin(slope);
t4 = r.*t2;
p0 = [-r.*t3-q0.*r.*t2;t4-q0.*r.*t3];
if nargout > 1
    t5 = sin(q0);
    t6 = a.*t5;
    t7 = cos(q0);
    pStar = [t6-r.*t3-q0.*r.*t2;t4-a.*t7-q0.*r.*t3];
end
if nargout > 2
    t8 = t4-a.*t7;
    t9 = cos(q1);
    t10 = t6-r.*t3;
    t11 = dq0.*t10;
    t12 = sin(q1);
    p1 = [t6+b.*t12-r.*t3-q0.*r.*t2;t4-a.*t7-b.*t9-q0.*r.*t3];
end
if nargout > 3
    dp0 = [-dq0.*r.*t2;-dq0.*r.*t3];
end
if nargout > 4
    dpStar = [-dq0.*t8;t11];
end
if nargout > 5
    dp1 = [-dq0.*t8+b.*dq1.*t9;t11+b.*dq1.*t12];
end
