function [KE,PE] = autoGen_energy_minimal(q0,q1,dq1,dq0,m0,m1,g,r,a,b,I0,I1,slope)
%AUTOGEN_ENERGY_MINIMAL
%    [KE,PE] = AUTOGEN_ENERGY_MINIMAL(Q0,Q1,DQ1,DQ0,M0,M1,G,R,A,B,I0,I1,SLOPE)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 10:05:38

t5 = cos(slope);
t8 = r.*t5;
t9 = cos(q0);
t10 = a.*t9;
t11 = cos(q1);
t2 = -dq0.*(t8-t10)+b.*dq1.*t11;
t7 = sin(slope);
t3 = -dq0.*(r.*t7-a.*sin(q0))+b.*dq1.*sin(q1);
t4 = dq0.^2;
t6 = r.^2;
KE = I0.*t4.*(1.0./2.0)+m0.*(t4.*t5.^2.*t6+t4.*t6.*t7.^2).*(1.0./2.0)+I1.*dq1.^2.*(1.0./2.0)+m1.*(t2.^2+t3.^2).*(1.0./2.0);
if nargout > 1
    PE = g.*m0.*(t8-q0.*r.*t7)-g.*m1.*(-t8+t10+b.*t11+q0.*r.*t7);
end
