function [ddq0,ddq1] = autoGen_dynamics_minimal(q0,q1,dq1,dq0,m0,m1,g,r,a,b,I0,I1,slope)
%AUTOGEN_DYNAMICS_MINIMAL
%    [DDQ0,DDQ1] = AUTOGEN_DYNAMICS_MINIMAL(Q0,Q1,DQ1,DQ0,M0,M1,G,R,A,B,I0,I1,SLOPE)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 10:05:36

t2 = b.^2;
t3 = m1.^2;
t4 = a.^2;
t5 = r.^2;
t6 = q1.*2.0;
t7 = q0-slope;
t8 = cos(t7);
t9 = dq1.^2;
t10 = sin(q0);
t11 = sin(slope);
t12 = q0.*2.0;
t13 = dq0.^2;
t14 = q0+slope-t6;
t15 = q0-q1;
t16 = sin(t15);
t17 = sin(t7);
t18 = q1-slope;
t19 = sin(t18);
t20 = -t6+t12;
t21 = I0.*I1.*2.0;
t22 = t2.*t3.*t4;
t23 = t2.*t3.*t5;
t24 = I1.*m1.*t4.*2.0;
t25 = I0.*m1.*t2.*2.0;
t26 = I1.*m0.*t5.*2.0;
t27 = I1.*m1.*t5.*2.0;
t28 = cos(t20);
t36 = slope.*2.0;
t29 = t6-t36;
t30 = cos(t29);
t31 = m0.*m1.*t2.*t5.*2.0;
t32 = cos(t14);
t33 = a.*r.*t2.*t3.*t32.*2.0;
t34 = t21+t22+t23+t24+t25+t26+t27+t31+t33-t2.*t3.*t4.*t28-t2.*t3.*t5.*t30-I1.*a.*m1.*r.*t8.*4.0-a.*r.*t2.*t3.*t8.*2.0;
t35 = 1.0./t34;
t37 = q1-t36;
t38 = sin(t37);
t39 = sin(q1);
t40 = sin(t20);
t41 = q0-q1+slope;
t42 = sin(t41);
t43 = q0-q1-slope;
t44 = sin(t43);
t45 = sin(t14);
ddq0 = -t35.*(a.*g.*t2.*t3.*sin(q0-t6)+g.*r.*t2.*t3.*sin(-slope+t6)+I1.*a.*g.*m1.*t10.*2.0-I1.*g.*m0.*r.*t11.*2.0-I1.*g.*m1.*r.*t11.*2.0+a.*g.*t2.*t3.*t10-g.*r.*t2.*t3.*t11+t2.*t3.*t4.*t13.*t40+a.*r.*t2.*t3.*t13.*t17-a.*r.*t2.*t3.*t13.*t45+b.*r.*t2.*t3.*t9.*t19.*2.0+I1.*a.*b.*m1.*t9.*t16.*2.0+I1.*a.*m1.*r.*t13.*t17.*2.0+I1.*b.*m1.*r.*t9.*t19.*2.0+a.*b.*t2.*t3.*t9.*t16.*2.0-g.*m0.*m1.*r.*t2.*t11.*2.0);
if nargout > 1
    ddq1 = -b.*m1.*t35.*(I0.*g.*t39.*2.0+g.*m0.*t5.*t38+g.*m0.*t5.*t39+g.*m1.*t4.*t39+g.*m1.*t5.*t38+g.*m1.*t5.*t39-g.*m1.*t4.*sin(-q1+t12)-I0.*a.*t13.*t16.*2.0+m1.*r.*t4.*t13.*sin(-q1-slope+t12)+a.*g.*m0.*r.*t42+a.*g.*m1.*r.*t42.*2.0-a.*g.*m0.*r.*t44+a.*g.*m1.*r.*t44-a.*m0.*t5.*t13.*t16.*2.0-a.*m1.*t4.*t13.*t16.*2.0-a.*m1.*t5.*t13.*t16-b.*m1.*t4.*t9.*t40-a.*g.*m1.*r.*sin(q0+q1-slope)-m1.*r.*t4.*t13.*t19.*3.0+a.*m1.*t5.*t13.*sin(q0+q1-t36)+b.*m1.*t5.*t9.*sin(t29)+a.*b.*m1.*r.*t9.*t45.*2.0);
end
