function [G,dG] = autoGen_getCoM(q1,q2,dq1,dq2,d,l)
%AUTOGEN_GETCOM
%    [G,DG] = AUTOGEN_GETCOM(Q1,Q2,DQ1,DQ2,D,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    12-Jul-2015 14:28:49

t2 = sin(q1);
t3 = cos(q1);
t4 = l.*t3;
t5 = cos(q2);
t6 = sin(q2);
G = [d.*t2.*(1.0./2.0)+d.*t6.*(1.0./2.0)-l.*t2;t4-d.*t3.*(1.0./2.0)-d.*t5.*(1.0./2.0)];
if nargout > 1
    dG = [dq1.*(t4-d.*t3).*(-1.0./2.0)+d.*dq2.*t5.*(1.0./2.0)-dq1.*l.*t3.*(1.0./2.0);dq1.*(d.*t2-l.*t2).*(1.0./2.0)+d.*dq2.*t6.*(1.0./2.0)-dq1.*l.*t2.*(1.0./2.0)];
end
