function [ddq,Fx,Fy] = autoGen_dynamics_minimal(m,g,r,I,slope)
%AUTOGEN_DYNAMICS_MINIMAL
%    [DDQ,FX,FY] = AUTOGEN_DYNAMICS_MINIMAL(M,G,R,I,SLOPE)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 08:53:37

t2 = r.^2;
t3 = m.*t2;
t4 = I+t3;
t5 = 1.0./t4;
t6 = sin(slope);
ddq = g.*m.*r.*t5.*t6;
if nargout > 1
    Fx = g.*m.^2.*t2.*t5.*sin(slope.*2.0).*(-1.0./2.0);
end
if nargout > 2
    Fy = g.*m.*t5.*(I+t3-m.*t2.*t6.^2);
end
