function [ddx,ddy,ddq,Fx,Fy] = autoGen_dynamics_contact(q,dq,th,ddpc_x,ddpc_y,m,g,r,I)
%AUTOGEN_DYNAMICS_CONTACT
%    [DDX,DDY,DDQ,FX,FY] = AUTOGEN_DYNAMICS_CONTACT(Q,DQ,TH,DDPC_X,DDPC_Y,M,G,R,I)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 08:58:27

t2 = r.^2;
t3 = q.*2.0;
t4 = th.*2.0;
t5 = t3+t4;
t6 = sin(t5);
t7 = dq.^2;
t8 = q+th;
t9 = sin(t8);
t10 = cos(t8);
t11 = t10.^2;
t12 = m.*t2;
t13 = I+t12;
t14 = 1.0./t13;
t15 = cos(t5);
ddx = (I.*ddpc_x.*2.0+ddpc_x.*m.*t2+I.*r.*t7.*t9.*2.0-ddpc_y.*m.*t2.*t6-ddpc_x.*m.*t2.*t15-g.*m.*t2.*t6+m.*r.*t2.*t7.*t9.*2.0)./(I.*2.0+m.*t2.*2.0);
if nargout > 1
    t16 = m.*r.*t2.*t7.*t10;
    t17 = ddpc_x.*m.*t2.*t6.*(1.0./2.0);
    t18 = I.*r.*t7.*t10;
    ddy = -t14.*(t16+t17+t18-I.*ddpc_y+g.*m.*t2-ddpc_y.*m.*t2.*t11-g.*m.*t2.*t11);
end
if nargout > 2
    ddq = m.*r.*t14.*(ddpc_x.*t10+ddpc_y.*t9+g.*t9);
end
if nargout > 3
    Fx = m.*t14.*(I.*ddpc_x+ddpc_x.*m.*t2.*(1.0./2.0)+I.*r.*t7.*t9-ddpc_y.*m.*t2.*t6.*(1.0./2.0)-ddpc_x.*m.*t2.*t15.*(1.0./2.0)-g.*m.*t2.*t6.*(1.0./2.0)+m.*r.*t2.*t7.*t9);
end
if nargout > 4
    Fy = m.*t14.*(-t16-t17-t18+I.*ddpc_y+I.*g+ddpc_y.*m.*t2.*t11+g.*m.*t2.*t11);
end
