function ddz = autoGen_dynamics(qf,qm,ql,dqf,dqm,dql,Ia,Rad,Len,Ecc,g,Jf,Jm,Jl,m,Km,Ks,Ga,C0,C1,Mu,Smooth,Cf)
%AUTOGEN_DYNAMICS
%    DDZ = AUTOGEN_DYNAMICS(QF,QM,QL,DQF,DQM,DQL,IA,RAD,LEN,ECC,G,JF,JM,JL,M,KM,KS,GA,C0,C1,MU,SMOOTH,CF)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    23-Aug-2015 16:19:34

t2 = Len.^2;
t3 = m.^2;
t4 = Ecc.^2;
t5 = Rad.^2;
t6 = ql.*2.0;
t7 = cos(qf);
t8 = qf-t6;
t9 = sin(qf);
t10 = qf.*2.0;
t11 = -t6+t10;
t12 = dql.^2;
t13 = qf-ql;
t14 = cos(t13);
t15 = dqf.^2;
t16 = sin(t8);
t17 = sin(ql);
t18 = sin(t13);
t19 = 1.0./Smooth;
t20 = dql-dqm;
t21 = t19.*t20;
t22 = tanh(t21);
t23 = cos(ql);
t24 = Ia.*t19;
t25 = tanh(t24);
t26 = Jf.*Jl.*2.0;
t27 = t2.*t3.*t4;
t28 = t2.*t3.*t5;
t29 = Jl.*m.*t4.*2.0;
t30 = Jf.*m.*t2.*2.0;
t31 = Jl.*m.*t5.*2.0;
t32 = cos(t6);
t33 = cos(t11);
t34 = cos(t8);
t35 = Ecc.*Rad.*t2.*t3.*t34.*2.0;
t36 = t26+t27+t28+t29+t30+t31+t35-t2.*t3.*t4.*t33-t2.*t3.*t5.*t32-Ecc.*Jl.*Rad.*m.*t7.*4.0-Ecc.*Rad.*t2.*t3.*t7.*2.0;
t37 = 1.0./t36;
t38 = sin(t6);
t39 = sin(t11);
t40 = -ql+t10;
t41 = sin(t40);
t42 = qf+ql;
t43 = sin(t42);
ddz = [-t37.*(Cf.*Jl.*dqf.*2.0+Jl.*Ks.*qf.*2.0-Jl.*Ks.*qm.*2.0+Cf.*dqf.*m.*t2.*2.0+Ks.*m.*qf.*t2.*2.0-Ks.*m.*qm.*t2.*2.0+Ecc.*Jl.*g.*m.*t9.*2.0+Ecc.*g.*t2.*t3.*t9+Ecc.*g.*t2.*t3.*t16+Rad.*g.*t2.*t3.*t38+t2.*t3.*t4.*t15.*t39+C1.*Ecc.*Len.*dql.*m.*t14.*2.0-C1.*Ecc.*Len.*dqm.*m.*t14.*2.0-C1.*Len.*Rad.*dql.*m.*t23.*2.0+C1.*Len.*Rad.*dqm.*m.*t23.*2.0+C0.*Ecc.*Len.*m.*t14.*t22.*2.0-Ecc.*Jl.*Len.*m.*t12.*t18.*2.0-C0.*Len.*Rad.*m.*t22.*t23.*2.0+Ecc.*Jl.*Rad.*m.*t9.*t15.*2.0-Jl.*Len.*Rad.*m.*t12.*t17.*2.0-Ecc.*Len.*t2.*t3.*t12.*t18.*2.0+Ecc.*Rad.*t2.*t3.*t9.*t15-Ecc.*Rad.*t2.*t3.*t15.*t16-Len.*Rad.*t2.*t3.*t12.*t17.*2.0+Ecc.*Ga.*Ia.*Km.*Len.*m.*t14.*2.0-Ga.*Ia.*Km.*Len.*Rad.*m.*t23.*2.0+Ecc.*Ga.*Ia.*Km.*Len.*Mu.*m.*t14.*t22.*t25.*2.0-Ga.*Ia.*Km.*Len.*Mu.*Rad.*m.*t22.*t23.*t25.*2.0);(1.0./Ga.^2.*(C1.*dql-C1.*dqm+C0.*t22+Ks.*qf-Ks.*qm+Ga.*Ia.*Km+Ga.*Ia.*Km.*Mu.*t22.*t25))./Jm;-t37.*(C1.*Jf.*dql.*2.0-C1.*Jf.*dqm.*2.0+C0.*Jf.*t22.*2.0+Ga.*Ia.*Jf.*Km.*2.0+C1.*dql.*m.*t4.*2.0+C1.*dql.*m.*t5.*2.0-C1.*dqm.*m.*t4.*2.0-C1.*dqm.*m.*t5.*2.0+C0.*m.*t4.*t22.*2.0+C0.*m.*t5.*t22.*2.0+Ga.*Ia.*Km.*m.*t4.*2.0+Ga.*Ia.*Km.*m.*t5.*2.0-Jf.*Len.*g.*m.*t17.*2.0-Len.*g.*t3.*t4.*t17-Len.*g.*t3.*t5.*t17.*2.0+Len.*g.*t3.*t4.*t41-t2.*t3.*t4.*t12.*t39+t2.*t3.*t5.*t12.*t38+Cf.*Ecc.*Len.*dqf.*m.*t14.*2.0-C1.*Ecc.*Rad.*dql.*m.*t7.*4.0+C1.*Ecc.*Rad.*dqm.*m.*t7.*4.0-Cf.*Len.*Rad.*dqf.*m.*t23.*2.0+Ecc.*Ks.*Len.*m.*qf.*t14.*2.0-Ecc.*Ks.*Len.*m.*qm.*t14.*2.0-C0.*Ecc.*Rad.*m.*t7.*t22.*4.0+Ecc.*Jf.*Len.*m.*t15.*t18.*2.0-Ecc.*Len.*Rad.*g.*t3.*t18.*3.0+Ecc.*Len.*Rad.*g.*t3.*t43-Ks.*Len.*Rad.*m.*qf.*t23.*2.0+Ks.*Len.*Rad.*m.*qm.*t23.*2.0+Ecc.*Len.*t3.*t4.*t15.*t18.*2.0+Ecc.*Len.*t3.*t5.*t15.*t18-Ecc.*Len.*t3.*t5.*t15.*t43+Ecc.*Rad.*t2.*t3.*t12.*t16.*2.0+Len.*Rad.*t3.*t4.*t15.*t17.*3.0-Len.*Rad.*t3.*t4.*t15.*t41-Ecc.*Ga.*Ia.*Km.*Rad.*m.*t7.*4.0+Ga.*Ia.*Jf.*Km.*Mu.*t22.*t25.*2.0+Ga.*Ia.*Km.*Mu.*m.*t4.*t22.*t25.*2.0+Ga.*Ia.*Km.*Mu.*m.*t5.*t22.*t25.*2.0-Ecc.*Ga.*Ia.*Km.*Mu.*Rad.*m.*t7.*t22.*t25.*4.0)];
