/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * autoGen_kinematicsContact.c
 *
 * Code generation for function 'autoGen_kinematicsContact'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulate.h"
#include "autoGen_kinematicsContact.h"

/* Function Definitions */

/*
 * function [p0c,p1c,dp0c,dp1c] = autoGen_kinematicsContact(x,y,phi0,phi1,th0,th1,dx,dy,dphi0,dphi1,dth0,dth1,qc0,qc1,rc0,rc1,l)
 */
void autoGen_kinematicsContact(double x, double y, double phi0, double phi1,
  double th0, double th1, double qc0, double qc1, double rc0, double rc1, double
  l, double p0c[2], double p1c[2])
{
  double t2;
  double t3;

  /* AUTOGEN_KINEMATICSCONTACT */
  /*     [P0C,P1C,DP0C,DP1C] = AUTOGEN_KINEMATICSCONTACT(X,Y,PHI0,PHI1,TH0,TH1,DX,DY,DPHI0,DPHI1,DTH0,DTH1,QC0,QC1,RC0,RC1,L) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.3. */
  /*     30-Jan-2016 13:22:37 */
  /* 'autoGen_kinematicsContact:8' t2 = phi0+qc0; */
  t2 = phi0 + qc0;

  /* 'autoGen_kinematicsContact:9' t3 = phi1+qc1; */
  t3 = phi1 + qc1;

  /* 'autoGen_kinematicsContact:10' t4 = cos(th0); */
  /* 'autoGen_kinematicsContact:11' t5 = cos(t2); */
  /* 'autoGen_kinematicsContact:12' t6 = sin(th0); */
  /* 'autoGen_kinematicsContact:13' t7 = sin(t2); */
  /* 'autoGen_kinematicsContact:14' p0c = [x+l.*t6+rc0.*t7;y-l.*t4-rc0.*t5]; */
  p0c[0] = (x + l * sin(th0)) + rc0 * sin(t2);
  p0c[1] = (y - l * cos(th0)) - rc0 * cos(t2);

  /* 'autoGen_kinematicsContact:15' if nargout > 1 */
  /* 'autoGen_kinematicsContact:16' t8 = cos(th1); */
  /* 'autoGen_kinematicsContact:17' t9 = cos(t3); */
  /* 'autoGen_kinematicsContact:18' t10 = sin(th1); */
  /* 'autoGen_kinematicsContact:19' t11 = sin(t3); */
  /* 'autoGen_kinematicsContact:20' p1c = [x+l.*t10+rc1.*t11;y-l.*t8-rc1.*t9]; */
  p1c[0] = (x + l * sin(th1)) + rc1 * sin(t3);
  p1c[1] = (y - l * cos(th1)) - rc1 * cos(t3);

  /* 'autoGen_kinematicsContact:22' if nargout > 2 */
  /* 'autoGen_kinematicsContact:25' if nargout > 3 */
}

/* End of code generation (autoGen_kinematicsContact.c) */
