/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * autoGen_dynamics_ds.c
 *
 * Code generation for function 'autoGen_dynamics_ds'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "simulate.h"
#include "autoGen_dynamics_ds.h"

/* Function Definitions */

/*
 * function [M_ds,f_ds] = autoGen_dynamics_ds(phi0,phi1,th0,th1,dphi0,dphi1,dth0,dth1,u0,u1,uHip,fx,fy,qc0,qc1,rc1,rc0,ddp1c_x,ddp1c_y,ddp0c_x,ddp0c_y,g,l,c,m,I,Ifoot,b)
 */
void autoGen_dynamics_ds(double phi0, double phi1, double th0, double th1,
  double dphi0, double dphi1, double dth0, double dth1, double u0, double u1,
  double uHip, double fx, double fy, double qc0, double qc1, double rc1, double
  rc0, double ddp1c_x, double ddp1c_y, double ddp0c_x, double ddp0c_y, double g,
  double l, double c, double m, double I, double Ifoot, double b, double M_ds
  [100], double f_ds[10])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;
  double t9;
  double t10;
  double t11;
  double t12;
  double t13;
  double t14;
  double t15;
  double t16;
  double t17;
  double t18;
  double t19;
  double t20;
  double t21;
  double x[100];
  double t22;
  double t23;
  double t24;
  double t25;
  double t26;
  double t27;

  /* AUTOGEN_DYNAMICS_DS */
  /*     [M_DS,F_DS] = AUTOGEN_DYNAMICS_DS(PHI0,PHI1,TH0,TH1,DPHI0,DPHI1,DTH0,DTH1,U0,U1,UHIP,FX,FY,QC0,QC1,RC1,RC0,DDP1C_X,DDP1C_Y,DDP0C_X,DDP0C_Y,G,L,C,M,I,IFOOT,B) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.3. */
  /*     30-Jan-2016 13:22:42 */
  /* 'autoGen_dynamics_ds:8' t2 = cos(th0); */
  t2 = cos(th0);

  /* 'autoGen_dynamics_ds:9' t3 = sin(th0); */
  t3 = sin(th0);

  /* 'autoGen_dynamics_ds:10' t4 = phi0+qc0; */
  t4 = phi0 + qc0;

  /* 'autoGen_dynamics_ds:11' t5 = cos(th1); */
  t5 = cos(th1);

  /* 'autoGen_dynamics_ds:12' t6 = sin(th1); */
  t6 = sin(th1);

  /* 'autoGen_dynamics_ds:13' t7 = c.^2; */
  /* 'autoGen_dynamics_ds:14' t8 = -I-m.*t7; */
  t8 = -I - m * (c * c);

  /* 'autoGen_dynamics_ds:15' t9 = phi1+qc1; */
  t9 = phi1 + qc1;

  /* 'autoGen_dynamics_ds:16' t10 = cos(t4); */
  t10 = cos(t4);

  /* 'autoGen_dynamics_ds:17' t11 = rc0.*t10; */
  t11 = rc0 * t10;

  /* 'autoGen_dynamics_ds:18' t12 = sin(t4); */
  t12 = sin(t4);

  /* 'autoGen_dynamics_ds:19' t13 = rc0.*t12; */
  t13 = rc0 * t12;

  /* 'autoGen_dynamics_ds:20' t14 = cos(t9); */
  t14 = cos(t9);

  /* 'autoGen_dynamics_ds:21' t15 = rc1.*t14; */
  t15 = rc1 * t14;

  /* 'autoGen_dynamics_ds:22' t16 = sin(t9); */
  t16 = sin(t9);

  /* 'autoGen_dynamics_ds:23' t17 = rc1.*t16; */
  t17 = rc1 * t16;

  /* 'autoGen_dynamics_ds:24' t18 = l.*t5; */
  t18 = l * t5;

  /* 'autoGen_dynamics_ds:25' t19 = l.*t6; */
  t19 = l * t6;

  /* 'autoGen_dynamics_ds:26' t20 = l.*t2; */
  t20 = l * t2;

  /* 'autoGen_dynamics_ds:27' t21 = l.*t3; */
  t21 = l * t3;

  /* 'autoGen_dynamics_ds:28' M_ds = reshape([m.*-2.0,0.0,-c.*m.*t2,-c.*m.*t5,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,m.*-2.0,-c.*m.*t3,-c.*m.*t6,0.0,0.0,0.0,-1.0,0.0,-1.0,0.0,0.0,-Ifoot,0.0,-Ifoot,0.0,0.0,0.0,-t11,-t13,0.0,0.0,0.0,-Ifoot,0.0,-Ifoot,-t15,-t17,0.0,0.0,-c.*m.*t2,-c.*m.*t3,t8,0.0,0.0,0.0,0.0,0.0,-t20,-t21,-c.*m.*t5,-c.*m.*t6,0.0,t8,0.0,0.0,-t18,-t19,0.0,0.0,1.0,0.0,0.0,t15+t18,0.0,t15,0.0,0.0,0.0,0.0,0.0,1.0,0.0,t17+t19,0.0,t17,0.0,0.0,0.0,0.0,1.0,0.0,t11+t20,0.0,t11,0.0,0.0,0.0,0.0,0.0,0.0,1.0,t13+t21,0.0,t13,0.0,0.0,0.0,0.0,0.0],[10,10]); */
  x[0] = m * -2.0;
  x[1] = 0.0;
  x[2] = -c * m * t2;
  x[3] = -c * m * t5;
  x[4] = 0.0;
  x[5] = 0.0;
  x[6] = -1.0;
  x[7] = 0.0;
  x[8] = -1.0;
  x[9] = 0.0;
  x[10] = 0.0;
  x[11] = m * -2.0;
  x[12] = -c * m * t3;
  x[13] = -c * m * t6;
  x[14] = 0.0;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = -1.0;
  x[18] = 0.0;
  x[19] = -1.0;
  x[20] = 0.0;
  x[21] = 0.0;
  x[22] = -Ifoot;
  x[23] = 0.0;
  x[24] = -Ifoot;
  x[25] = 0.0;
  x[26] = 0.0;
  x[27] = 0.0;
  x[28] = -t11;
  x[29] = -t13;
  x[30] = 0.0;
  x[31] = 0.0;
  x[32] = 0.0;
  x[33] = -Ifoot;
  x[34] = 0.0;
  x[35] = -Ifoot;
  x[36] = -t15;
  x[37] = -t17;
  x[38] = 0.0;
  x[39] = 0.0;
  x[40] = -c * m * t2;
  x[41] = -c * m * t3;
  x[42] = t8;
  x[43] = 0.0;
  x[44] = 0.0;
  x[45] = 0.0;
  x[46] = 0.0;
  x[47] = 0.0;
  x[48] = -t20;
  x[49] = -t21;
  x[50] = -c * m * t5;
  x[51] = -c * m * t6;
  x[52] = 0.0;
  x[53] = t8;
  x[54] = 0.0;
  x[55] = 0.0;
  x[56] = -t18;
  x[57] = -t19;
  x[58] = 0.0;
  x[59] = 0.0;
  x[60] = 1.0;
  x[61] = 0.0;
  x[62] = 0.0;
  x[63] = t15 + t18;
  x[64] = 0.0;
  x[65] = t15;
  x[66] = 0.0;
  x[67] = 0.0;
  x[68] = 0.0;
  x[69] = 0.0;
  x[70] = 0.0;
  x[71] = 1.0;
  x[72] = 0.0;
  x[73] = t17 + t19;
  x[74] = 0.0;
  x[75] = t17;
  x[76] = 0.0;
  x[77] = 0.0;
  x[78] = 0.0;
  x[79] = 0.0;
  x[80] = 1.0;
  x[81] = 0.0;
  x[82] = t11 + t20;
  x[83] = 0.0;
  x[84] = t11;
  x[85] = 0.0;
  x[86] = 0.0;
  x[87] = 0.0;
  x[88] = 0.0;
  x[89] = 0.0;
  x[90] = 0.0;
  x[91] = 1.0;
  x[92] = t13 + t21;
  x[93] = 0.0;
  x[94] = t13;
  x[95] = 0.0;
  x[96] = 0.0;
  x[97] = 0.0;
  x[98] = 0.0;
  x[99] = 0.0;
  memcpy(&M_ds[0], &x[0], 100U * sizeof(double));

  /* 'autoGen_dynamics_ds:29' if nargout > 1 */
  /* 'autoGen_dynamics_ds:30' t22 = dth0.^2; */
  t22 = dth0 * dth0;

  /* 'autoGen_dynamics_ds:31' t23 = dth1.^2; */
  t23 = dth1 * dth1;

  /* 'autoGen_dynamics_ds:32' t24 = b.*dphi0; */
  t24 = b * dphi0;

  /* 'autoGen_dynamics_ds:33' t25 = b.*dphi1; */
  t25 = b * dphi1;

  /* 'autoGen_dynamics_ds:34' t26 = dphi1.^2; */
  t26 = dphi1 * dphi1;

  /* 'autoGen_dynamics_ds:35' t27 = dphi0.^2; */
  t27 = dphi0 * dphi0;

  /* 'autoGen_dynamics_ds:36' f_ds = [-fx-m.*(c.*t3.*t22.*(1.0./2.0)+c.*t6.*t23.*(1.0./2.0)).*2.0;-fy+g.*m.*2.0+m.*(c.*t2.*t22.*(1.0./2.0)+c.*t5.*t23.*(1.0./2.0)).*2.0;t24+uHip+c.*g.*m.*t3;t25-uHip+c.*g.*m.*t6;t24+u0;t25+u1;-ddp1c_x-l.*t6.*t23-rc1.*t16.*t26;-ddp1c_y+l.*t5.*t23+rc1.*t14.*t26;-ddp0c_x-l.*t3.*t22-rc0.*t12.*t27;-ddp0c_y+l.*t2.*t22+rc0.*t10.*t27]; */
  f_ds[0] = -fx - m * (c * t3 * t22 * 0.5 + c * t6 * t23 * 0.5) * 2.0;
  f_ds[1] = (-fy + g * m * 2.0) + m * (c * t2 * t22 * 0.5 + c * t5 * t23 * 0.5) *
    2.0;
  f_ds[2] = (t24 + uHip) + c * g * m * t3;
  f_ds[3] = (t25 - uHip) + c * g * m * t6;
  f_ds[4] = t24 + u0;
  f_ds[5] = t25 + u1;
  f_ds[6] = (-ddp1c_x - l * t6 * t23) - rc1 * t16 * t26;
  f_ds[7] = (-ddp1c_y + l * t5 * t23) + rc1 * t14 * t26;
  f_ds[8] = (-ddp0c_x - l * t3 * t22) - rc0 * t12 * t27;
  f_ds[9] = (-ddp0c_y + l * t2 * t22) + rc0 * t10 * t27;
}

/* End of code generation (autoGen_dynamics_ds.c) */
