function [ddp0c,ddp1c] = autoGen_kinematicsContactAccel(phi0,phi1,th0,th1,dphi0,dphi1,dth0,dth1,ddx,ddy,ddphi0,ddphi1,ddth0,ddth1,qc0,qc1,rc0,rc1,l)
%AUTOGEN_KINEMATICSCONTACTACCEL
%    [DDP0C,DDP1C] = AUTOGEN_KINEMATICSCONTACTACCEL(PHI0,PHI1,TH0,TH1,DPHI0,DPHI1,DTH0,DTH1,DDX,DDY,DDPHI0,DDPHI1,DDTH0,DDTH1,QC0,QC1,RC0,RC1,L)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Jan-2016 13:22:38

t2 = phi0+qc0;
t3 = sin(th0);
t4 = dphi0.^2;
t5 = cos(t2);
t6 = dth0.^2;
t7 = cos(th0);
t8 = sin(t2);
ddp0c = [ddx+ddth0.*l.*t7+ddphi0.*rc0.*t5-l.*t3.*t6-rc0.*t4.*t8;ddy+ddth0.*l.*t3+ddphi0.*rc0.*t8+l.*t6.*t7+rc0.*t4.*t5];
if nargout > 1
    t9 = phi1+qc1;
    t10 = sin(th1);
    t11 = dphi1.^2;
    t12 = cos(t9);
    t13 = dth1.^2;
    t14 = cos(th1);
    t15 = sin(t9);
    ddp1c = [ddx+ddth1.*l.*t14+ddphi1.*rc1.*t12-l.*t10.*t13-rc1.*t11.*t15;ddy+ddth1.*l.*t10+ddphi1.*rc1.*t15+l.*t13.*t14+rc1.*t11.*t12];
end
