function [M_s1,f_s1] = autoGen_dynamics_s1(th0,th1,phi1,dth0,dth1,dphi1,u0,u1,uHip,fx,fy,qc1,rc1,ddp1c_x,ddp1c_y,g,l,c,m,I,Ifoot,b)
%AUTOGEN_DYNAMICS_S1
%    [M_S1,F_S1] = AUTOGEN_DYNAMICS_S1(TH0,TH1,PHI1,DTH0,DTH1,DPHI1,U0,U1,UHIP,FX,FY,QC1,RC1,DDP1C_X,DDP1C_Y,G,L,C,M,I,IFOOT,B)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Jan-2016 13:22:40

t2 = cos(th0);
t3 = sin(th0);
t4 = cos(th1);
t5 = sin(th1);
t6 = c.^2;
t7 = -I-m.*t6;
t8 = phi1+qc1;
t9 = cos(t8);
t10 = rc1.*t9;
t11 = sin(t8);
t12 = rc1.*t11;
t13 = l.*t4;
t14 = l.*t5;
M_s1 = reshape([m.*-2.0,0.0,-c.*m.*t2,-c.*m.*t4,0.0,0.0,-1.0,0.0,0.0,m.*-2.0,-c.*m.*t3,-c.*m.*t5,0.0,0.0,0.0,-1.0,0.0,0.0,-Ifoot,0.0,-Ifoot,0.0,0.0,0.0,0.0,0.0,0.0,-Ifoot,0.0,-Ifoot,-t10,-t12,-c.*m.*t2,-c.*m.*t3,t7,0.0,0.0,0.0,0.0,0.0,-c.*m.*t4,-c.*m.*t5,0.0,t7,0.0,0.0,-t13,-t14,1.0,0.0,0.0,t10+t13,0.0,t10,0.0,0.0,0.0,1.0,0.0,t12+t14,0.0,t12,0.0,0.0],[8,8]);
if nargout > 1
    t15 = dth0.^2;
    t16 = dth1.^2;
    t17 = b.*dphi1;
    t18 = dphi1.^2;
    f_s1 = [-fx-c.*m.*t3.*t15-c.*m.*t5.*t16;-fy+g.*m.*2.0+c.*m.*t2.*t15+c.*m.*t4.*t16;uHip+c.*g.*m.*t3;t17-uHip+c.*g.*m.*t5;u0;t17+u1;-ddp1c_x-l.*t5.*t16-rc1.*t11.*t18;-ddp1c_y+l.*t4.*t16+rc1.*t9.*t18];
end
