function [M,f] = autoGen_dynamics(phi0,phi1,th0,th1,dth0,dth1,u0,u1,uHip,F0x,F0y,F1x,F1y,qc0,qc1,rc0,rc1,g,l,c,m,I,Ifoot)
%AUTOGEN_DYNAMICS
%    [M,F] = AUTOGEN_DYNAMICS(PHI0,PHI1,TH0,TH1,DTH0,DTH1,U0,U1,UHIP,F0X,F0Y,F1X,F1Y,QC0,QC1,RC0,RC1,G,L,C,M,I,IFOOT)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    17-Jul-2015 13:53:30

t2 = cos(th0);
t3 = sin(th0);
t4 = cos(th1);
t5 = sin(th1);
t6 = c.^2;
t7 = -I-m.*t6;
M = reshape([m.*-2.0,0.0,-c.*m.*t2,-c.*m.*t4,0.0,0.0,0.0,m.*-2.0,-c.*m.*t3,-c.*m.*t5,0.0,0.0,0.0,0.0,-Ifoot,0.0,-Ifoot,0.0,0.0,0.0,0.0,-Ifoot,0.0,-Ifoot,-c.*m.*t2,-c.*m.*t3,t7,0.0,0.0,0.0,-c.*m.*t4,-c.*m.*t5,0.0,t7,0.0,0.0],[6, 6]);
if nargout > 1
    t8 = dth0.^2;
    t9 = dth1.^2;
    t10 = phi0+qc0;
    t11 = phi1+qc1;
    t12 = cos(t10);
    t13 = sin(t10);
    t14 = cos(t11);
    t15 = sin(t11);
    f = [-F0x-F1x-m.*(c.*t3.*t8.*(1.0./2.0)+c.*t5.*t9.*(1.0./2.0)).*2.0;-F0y-F1y+g.*m.*2.0+m.*(c.*t2.*t8.*(1.0./2.0)+c.*t4.*t9.*(1.0./2.0)).*2.0;uHip-F0x.*l.*t2-F0y.*l.*t3-F0x.*rc0.*t12-F0y.*rc0.*t13+c.*g.*m.*t3;-uHip-F1x.*l.*t4-F1y.*l.*t5-F1x.*rc1.*t14-F1y.*rc1.*t15+c.*g.*m.*t5;u0-F0x.*rc0.*t12-F0y.*rc0.*t13;u1-F1x.*rc1.*t14-F1y.*rc1.*t15];
end
