function [MM,ff] = autoGen_gravityCompensation(q0,q1,q2,dq0,dq1,dq2,l,c,r,m,g,I)
%AUTOGEN_GRAVITYCOMPENSATION
%    [MM,FF] = AUTOGEN_GRAVITYCOMPENSATION(Q0,Q1,Q2,DQ0,DQ1,DQ2,L,C,R,M,G,I)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    14-Jul-2015 11:45:27

t2 = cos(q1);
t3 = l.*t2;
t4 = cos(q0);
t5 = r.*t4;
t6 = sin(q1);
t7 = c-l;
t8 = l.*t6;
t9 = sin(q0);
t10 = r.*t9;
t11 = c.^2;
t12 = q1-q2;
t13 = cos(t12);
t14 = c.*l.*m.*t13;
t18 = c.*t6;
t15 = t8+t10-t18;
t16 = sin(q2);
t25 = c.*t16;
t17 = t8+t10-t25;
t19 = dq1.^2;
t20 = dq0.^2;
t21 = t3+t5-c.*t2;
t22 = cos(q2);
t23 = t3+t5-c.*t22;
MM = reshape([0.0,-1.0,0.0,-I-l.*m.*t6.*t17-l.*m.*t2.*t23+m.*t6.*t7.*t15+m.*t2.*t7.*t21,-I+t14-m.*t11-l.^2.*m.*2.0+c.*l.*m.*2.0,-I+t14-m.*t11+c.*l.*m,0.0,0.0,1.0],[3, 3]);
if nargout > 1
    t24 = r.*t9.*t20;
    t26 = dq2.^2;
    t27 = r.*t4.*t20;
    t28 = sin(t12);
    t29 = q0-q1;
    t30 = sin(t29);
    t31 = q0-q2;
    t32 = sin(t31);
    ff = [m.*t17.*(t27-c.*t22.*t26+l.*t2.*t19)-m.*t23.*(t24-c.*t16.*t26+l.*t6.*t19)-m.*t21.*(t24+t19.*(t8-t18))-g.*m.*t15-g.*m.*t17+m.*t15.*(t27+t19.*(t3-c.*t2));m.*(c.*g.*t6+c.*g.*t16-g.*l.*t6.*2.0+c.*l.*t19.*t28-c.*l.*t26.*t28+c.*r.*t20.*t30+c.*r.*t20.*t32-l.*r.*t20.*t30.*2.0);c.*m.*(g.*t6+g.*t16+l.*t19.*t28+r.*t20.*t30+r.*t20.*t32)];
end
