function [p0,p1,dp0,dp1,ddp0,ddp1] = autoGen_kinematics(x,y,th0,th1,dx,dy,dth0,dth1,ddx,ddy,ddth0,ddth1,l)
%AUTOGEN_KINEMATICS
%    [P0,P1,DP0,DP1,DDP0,DDP1] = AUTOGEN_KINEMATICS(X,Y,TH0,TH1,DX,DY,DTH0,DTH1,DDX,DDY,DDTH0,DDTH1,L)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    30-Jan-2016 13:22:37

t2 = cos(th0);
t3 = sin(th0);
p0 = [x+l.*t3;y-l.*t2];
if nargout > 1
    t4 = cos(th1);
    t5 = sin(th1);
    p1 = [x+l.*t5;y-l.*t4];
end
if nargout > 2
    dp0 = [dx+dth0.*l.*t2;dy+dth0.*l.*t3];
end
if nargout > 3
    dp1 = [dx+dth1.*l.*t4;dy+dth1.*l.*t5];
end
if nargout > 4
    t6 = dth0.^2;
    ddp0 = [ddx+ddth0.*l.*t2-l.*t3.*t6;ddy+ddth0.*l.*t3+l.*t2.*t6];
end
if nargout > 5
    t7 = dth1.^2;
    ddp1 = [ddx+ddth1.*l.*t4-l.*t5.*t7;ddy+ddth1.*l.*t5+l.*t4.*t7];
end
