function [pc,dpc] = autoGen_contactPoint(x,y,q0,dx,dy,dq0,th,r)
%AUTOGEN_CONTACTPOINT
%    [PC,DPC] = AUTOGEN_CONTACTPOINT(X,Y,Q0,DX,DY,DQ0,TH,R)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Aug-2015 16:00:16

t2 = q0+th;
t3 = cos(t2);
t4 = sin(t2);
pc = [x+r.*t4;y-r.*t3];
if nargout > 1
    dpc = [dx+dq0.*r.*t3;dy+dq0.*r.*t4];
end
